# Generated by Django 4.2.10 on 2024-03-01 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_comment_challenge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='exceprt',
            new_name='excerpt',
        ),
    ]
